version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      actions:
        patterns: ['*']
    schedule:
      interval: monthly
  - package-ecosystem: uv
    directory: /
    groups:
      build-tools:
        patterns: ['*']
    schedule:
      interval: monthly
